// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'labelsRow': string;
  'list': string;
  'listimage': string;
  'listname': string;
  'listpara': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
