// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeListItemWrapper': string;
  'curItem': string;
  'dynamicContent': string;
  'expand': string;
  'itemCompContent': string;
  'itemCompWrapper': string;
  'itemHeaderWrapper': string;
  'listHeaderImg': string;
  'listHeaderName': string;
  'listItemWrapper': string;
  'shrink': string;
  'tagName': string;
  'tagWrapper': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
