// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'bfFont': string;
  'cloudBackground': string;
  'img': string;
  'portrait': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
